### PR TITLE
New `skins_not_grouped.json` endpoint

### PR DESCRIPTION
**Pull request by ByMykel**
Working on #38 

- [x] Creat new `skins_not_grouped.json` endpoint.
- [x] Add `market_hash_name` attribute.
- [x] Add Souvenir skins.
- [x] Check and fix `name` translations in other languages for gloves, knives, stattrak skins, etc.

### CODE REVIEW

**Comment by ByMykel** [comment]
@RatzeR check the new endpoint [skins_not_grouped.json](https://raw.githubusercontent.com/ByMykel/CSGO-API/09b1054120485abaece2c3b3c05c04a990f5469d/public/api/en/skins_not_grouped.json). I tried to remove all the possible attributes, and if someone wants more info they can fetch by `skin_id`.

I have decided that is better to have this endpoint (`skins_not_grouped.json`) in [all.json](https://raw.githubusercontent.com/ByMykel/CSGO-API/09b1054120485abaece2c3b3c05c04a990f5469d/public/api/en/all.json) rather than [skins.json](https://raw.githubusercontent.com/ByMykel/CSGO-API/09b1054120485abaece2c3b3c05c04a990f5469d/public/api/en/skins.json) so these  API REST endpoints bellow could be used:

- Search by queries like "doppler factory new".
https://cs2-api.vercel.app/api/search?q=Stained

- Could list all items without grouping them.
https://cs2-api.vercel.app/api/items

- And get a determined item by id.
https://cs2-api.vercel.app/api/items?id=skin-69760

**Comment by ByMykel** [comment]
If I'm not missing something this should be done and resolves #38

**Comment by RatzeR** [comment]
Hi @ByMykel, 

looks great! 
I just found one/two little things:

I think in case of a Stattrack or Souvenir the correct structure is:

Desert Eagle (Souvenir) | Urban Rubble (Factory New)
and
Desert Eagle (StatTrak™) | Hypnotic (Factory New)

The rest seems to be fine! :-)

I also really like the crates extension in the skin.json!

**Comment by ByMykel** [comment]
@RatzeR The translations are different in every language.

I have checked very fast all the languages and write them here [utils/translations.json](https://github.com/ByMykel/CSGO-API/blob/5f45146530817463bcde4132d09873a9d319f862/utils/translations.json).

>Desert Eagle (Souvenir) | Urban Rubble (Factory New)
and
Desert Eagle (StatTrak™) | Hypnotic (Factory New)

These are for German language and look equal to your example.
```json
{
    "collectible_genuine": "{item_name} ({genuine})",
    "rare_special": "{item_name} (★) | {pattern}",
    "rare_special_with_wear": "{item_name} (★) | {pattern} ({wear})",
    "rare_special_with_wear_stattrak": "{item_name} (★ StatTrak™) | {pattern} ({wear})",
    "rare_special_vanilla": "{item_name} (★)",
    "rare_special_vanilla_stattrak": "{item_name} (★ StatTrak™)",
    "skin": "{item_name} | {pattern} ({wear})",
    "skin_stattrak": "{item_name} (StatTrak™) | {pattern} ({wear})",
    "skin_souvenir": "{item_name} (Souvenir) | {pattern} ({wear})"
}
```

**Pull request merged**
