### PR TITLE
additional data for all items

### PR DESCRIPTION
**Pull request by vladdnepr**
fixed readme

### CODE REVIEW

**Comment by ByMykel** [comment]
You said in #50 that `name_original` is a unique id, but now I'm seeing that is repeated.

Try to explain me where are you using the `name_original` and `rarity_original` without any details of your project, so we can find a better name and I see any reason to add these.

**Comment by vladdnepr** [comment]
name_original is mnemonic name for skin

for Desert Eagle it is weapon_deagle

> You said in https://github.com/ByMykel/CSGO-API/pull/50 that name_original is a unique id

 I said
> name is unique mnemonic ID of sticker.

As I said before your `name` must be `title`, and `name_original ` must be `name`

But `name` now is reserved, I dont know better than `name_original `

Also your `rarity` must be like `rarity_title`, and `rarity_original` must be `rarity_name`

I want to store mnemonic names in the db. I want to fetch for example all  `weapon_deagle`. Your `name` field contain localized string, so it cannot be used for search

**Comment by vladdnepr** [comment]
Please wait, market_hash_name must be always EN. I fix it

**Comment by ByMykel** [comment]
@vladdnepr check #58

I've deleted `name_original`, is still does not convince me. In `skins.js` and `skinsNotGrouped.js` you name it as the weapon weapon_xm1014, weapon_deagle, etc.

If you want the `name_origin` back please explain it to me (in an issue) how you use it, for example if you use it as an `id`, lets improve the actual `id` so it could be useful for you and other that use de API.

Also keep in mind that you can fork the repo and deploy it yourself very easily.

**Comment by vladdnepr** [comment]
Ok. I will use fork. I'm tired of arguing

**Comment by ByMykel** [comment]
My comment was not meant to be bad. It's just that I would like to know some examples when implementing something new that I don't see the purpose.

The only thing I don't understood is the `name_origin` the rest were good suggestions.

But yeah, in not a bad way, I think is better to use a fork if you are not willing to open an issue.

**Pull request closed without merging**
