### PR TITLE
Small changes and fix for one item

### PR DESCRIPTION
**Pull request by easton36**
I changed all of the JSON `import` statements to use the keyword `with` instead of `assert` since that is the new valid keyword. Not sure which node version github workflow runs since I am not familiar with it.

I added color `6` (Tracer Yellow) for the item `Sealed Graffiti | Recoil AUG` because it didn't exist in the scripts. I am not sure how you know which colors each graffiti has, but I would like to know where you are getting that info from so we can make this more accurate.

### CODE REVIEW

**Comment by ByMykel** [comment]
>Not sure which node version github workflow runs since I am not familiar with it.

Hi. The workflows run on node 18.

>I added color 6 (Tracer Yellow) for the item Sealed Graffiti | Recoil AUG because it didn't exist in the scripts. I am not sure how you know which colors each graffiti has, but I would like to know where you are getting that info from so we can make this more accurate.

I added all the sealed graffiti checking [csmoney wiki](https://wiki.cs.money/search?q=Graffiti%20%7C%20Recoil%20AUG), but seems like they don't have all the colors.

After adding them to the script I have to add the images to this [repo](https://github.com/ByMykel/counter-strike-image-tracker/tree/main/static/panorama/images/econ/stickers/default2020).

I haven't found a way to automate all of this. You can check the discussion about this here: https://github.com/ByMykel/CSGO-API/discussions/109

BTW I can't check the changes as you might pushed all the JSON files:
image

**Comment by easton36** [comment]
My bad. This is the only important change: https://github.com/ByMykel/CSGO-API/pull/120/commits/c0d8be94c55efd4a6dd5441a9f0eb9d09668ca83

**Comment by ByMykel** [comment]
> My bad. This is the only important change: [c0d8be9](https://github.com/ByMykel/CSGO-API/commit/c0d8be94c55efd4a6dd5441a9f0eb9d09668ca83)

Do you mind removing you last commit and leaving only the Sealed Graffiti change?

**Comment by easton36** [comment]
Done, sorry for the late reply

**Pull request merged**
