### PR TITLE
fix: description on skins, stickers, patches, graffiti and remove unused keys.

### PR DESCRIPTION
**Pull request by piyanggoon**

### CODE REVIEW

**Comment by piyanggoon** [comment]
Should we use "<br><br>" then "\\n\\n" ?

> This sticker can be applied to any weapon you own and can be scraped to look more worn. You can scrape the same sticker multiple times, making it a bit more worn each time, until it is removed from the weapon.<br><br>This foil sticker was autographed by professional player Eric Hoag playing for Team Liquid at DreamHack Cluj-Napoca 2015.\\n\\n50% of the proceeds from the sale of this sticker support the included players and organizations.

**Comment by piyanggoon** [comment]
>     {
        "id": "key-4904",
        "name": null,
        "description": "This key will open any Valve Series Weapon Case. Non-Valve Series cases (e.g. eSports Case) require their own key to open.",
        "crates": [
            {
                "id": "crate-4905",
                "name": null
            }
        ]
    },

**Comment by ByMykel** [comment]
Thanks, will check it this afternoon

**Comment by ByMykel** [comment]
LGTM. Thank you for the PR. ❤️

**Pull request merged**
